### ISSUE TITLE
Sending wont work

### ISSUE THREAD

**Issue by Seecomp** [EpokTarren/discordWebhookSender#1]
It wont send it would just popup " "

**Comment by EpokTarren** [comment]
How were you using it? What steps are needed for replication?

**Comment by Seecomp** [comment]
im using php 7.4

**Comment by EpokTarren** [comment]
This is not a PHP project. I'm not sure how you would even use PHP with it as anything other than a static file host. As long as the files are hosted it should work fine, you could also just use it from the GitHub pages page for the project [here](https://epoktarren.github.io/discordWebhookSender/).
